### ISSUE TITLE
Support for buildpack with cflinuxfs3 stack

### ISSUE THREAD

**Issue by jochenehret** [cloudfoundry-incubator/admin-ui#187] opened 2018-12-28 10:29 UTC
Hi Admin-UI developers,

can you please add support for a newer ruby-buildpack which is associated with the cflinuxfs3 stack? See https://github.com/cloudfoundry/ruby-buildpack/releases for all releases. This implies that you migrate from Ruby 2.4.2 to e.g. 2.4.4 as 2.4.2 is not supported in the latest buildpack releases.

Thanks and Best Regards,

  Jovan & Jochen.

**Comment by rboykin** [comment] 2019-01-09 10:42
This is a duplicate of issue https://github.com/cloudfoundry-incubator/admin-ui/issues/186.

**Closed by rboykin** 2019-01-09 10:42 UTC

**Comment by rboykin** [comment] 2019-01-10 11:41
@jochenehret Updated admin ui to use ruby 2.4.5 via commit https://github.com/cloudfoundry-incubator/admin-ui/commit/6fb23db8e71a055b2090e031cbb879ad692dae06
